# EDA
- Vamos a visualizar la información que tenemos disponible en los archivos

In [16]:
# Cargamos librerías
import pandas as pd
import os

In [17]:
df = pd.read_csv('../ENACOM_Data_Analyst/ENACOM_data/indicadores_macro.csv', index_col= 0)
df

     Año  Trimestre  IPC US  IPC AR USDARS oficial USDARS blue PBI millones
0   2013          1  232773     298           5,00        9,00    2.888.981
1   2013          2  233504     309           5,00        9,00    3.387.811
2   2013          3  234149     331           6,00       10,00    3.436.547
3   2013          4  233049     351           6,00       11,00    3.679.896
4   2014          1  236293     402           8,00       11,00    3.917.649
5   2014          2  238343     433           8,00       13,00    4.702.630
6   2014          3  238031     461           8,00       14,00    4.685.503
7   2014          4  234812     491           9,00       13,00    5.010.564
8   2015          1  236119     518           9,00       13,00    5.092.694
9   2015          2  238638     549           9,00       15,00    5.951.479
10  2015          3  237945     584           9,00       15,00    6.221.731
11  2015          4  236525     621          10,00       15,00    6.552.140
12  2016          1  238132     697          14,00       15,00    6.962.845
13  2016          2  241038     751          14,00       15,00    8.401.125
14  2016          3  241428     791          15,00       16,00    8.448.890
15  2016          4  241432     833          15,00       16,00    8.942.135
16  2017          1  243801     880          16,00       16,00    9.157.377
17  2017          2  244955     925          16,00       18,00   10.595.155
18  2017          3  246819     963          17,00       18,00   10.937.240
19  2017          4  246524    1014          18,00       20,00   11.533.613
20  2018          1  249554    1083          20,00       24,00   11.975.804
21  2018          2  251989    1169          24,00       29,00          NaN

In [18]:
# Ruta de la carpeta con archivos
path_data = '../ENACOM_Data_Analyst/ENACOM_data/'

# Obtener un listado con todos los archivos de la carpeta
lista_archivos_cvs = os.listdir(path_data)
lista_archivos_cvs

['internet_fijo_poblacion_hogar.csv',
 'internet_fijo_tecno_loc.csv',
 'internet_tecno_nacional.csv',
 'internet_fijo_veloc_bajada_prov.csv',
 'indicadores_macro.csv',
 'internet_rango_vel_prov.csv',
 'internet_rango_vel.csv',
 'tecnologia_loc.csv',
 'internet_tecno_prov.csv',
 'veloc_media_prov.csv',
 'internet_bancha_bangosta.csv',
 'internet_fijo_veloc_bajada_loc.csv',
 'internet_fijo_poblacion.csv',
 'ingreso_internet_fijo_trimestral.csv',
 'internet_fijo_hogar.csv',
 'veloc_media_nacional.csv',
 'loc_tipo_conexion.csv',
 'internet_bancha_bangosta_prov.csv']

In [19]:
len(lista_archivos_cvs)

18

In [20]:
# Con esta función genero una tubla separando nombre y extension
os.path.splitext(lista_archivos_cvs[0])

('internet_fijo_poblacion_hogar', '.csv')

In [21]:
# Puedo seleccionar solo el nombre para guardarlo para nombrar los df
os.path.splitext(lista_archivos_cvs[0])[0]

'internet_fijo_poblacion_hogar'

In [22]:
path_data + lista_archivos_cvs[0]

'../ENACOM_Data_Analyst/ENACOM_data/internet_fijo_poblacion_hogar.csv'

In [23]:
# Realizo un diccionario de dataframes
dic_df_archivos = {}
for archivo in lista_archivos_cvs:
    df_temp = pd.read_csv(path_data + archivo, index_col= 0)
    nombre = os.path.splitext(archivo)[0]
    dic_df_archivos[nombre] = df_temp

In [24]:
# Retiro el contenido del diccionario como Dataframes independientes
for df_name, df in dic_df_archivos.items():
    globals()[df_name] = df

## Revision de archivos

In [25]:
# Veamos la cantidad de información de cada archivo
print(f'----------------------------------------------------')
print(f'|{"Nombre":35}|{"Filas":5}|{"Columnas":8}|')

for df_name, df in dic_df_archivos.items():
    print(f'|-----------------------------------|-----|--------|')
    print(f'|{df_name:35}|{df.shape[0]:5}|{df.shape[1]:8}|')

print(f'----------------------------------------------------')

----------------------------------------------------
|Nombre                             |Filas|Columnas|
|-----------------------------------|-----|--------|
|internet_fijo_poblacion_hogar      |   35|       5|
|-----------------------------------|-----|--------|
|internet_fijo_tecno_loc            | 3142|      14|
|-----------------------------------|-----|--------|
|internet_tecno_nacional            |   35|       9|
|-----------------------------------|-----|--------|
|internet_fijo_veloc_bajada_prov    |  481|      97|
|-----------------------------------|-----|--------|
|indicadores_macro                  |   22|       7|
|-----------------------------------|-----|--------|
|internet_rango_vel_prov            |  840|      12|
|-----------------------------------|-----|--------|
|internet_rango_vel                 |   35|      12|
|-----------------------------------|-----|--------|
|tecnologia_loc                     | 4312|      16|
|-----------------------------------|-----|--------|
|internet_tecno_prov                |  841|       9|
|-----------------------------------|-----|--------|
|veloc_media_prov                   |  840|       6|
|-----------------------------------|-----|--------|
|internet_bancha_bangosta           |   35|       6|
|-----------------------------------|-----|--------|
|internet_fijo_veloc_bajada_loc     | 3098|      83|
|-----------------------------------|-----|--------|
|internet_fijo_poblacion            |  840|       4|
|-----------------------------------|-----|--------|
|ingreso_internet_fijo_trimestral   |   35|       4|
|-----------------------------------|-----|--------|
|internet_fijo_hogar                |  840|       4|
|-----------------------------------|-----|--------|
|veloc_media_nacional               |   35|       4|
|-----------------------------------|-----|--------|
|loc_tipo_conexion                  | 4312|      12|
|-----------------------------------|-----|--------|
|internet_bancha_bangosta_prov      |  840|       6|
----------------------------------------------------

In [26]:
for df_name, df in dic_df_archivos.items():
    print(f"-------------------  {df_name}  ---------------------")
    print(f"{df.head(2)}\n")

-------------------  internet_fijo_poblacion_hogar  ---------------------
    Año  Trimestre Accesos por cada 100 hogares Accesos por cada 100 hab  \
0  2022          3                        76,64                    23,95
1  2022          2                        75,97                    23,72

         Periodo
0  Jul-Sept 2022
1   Abr-Jun 2022

-------------------  internet_fijo_tecno_loc  ---------------------
      Provincia     Partido   Localidad Link Indec ADSL CABLEMODEM DIAL UP  \
0  BUENOS AIRES  25 de Mayo  25 de Mayo    6854100  873      4.704     - 0
1  BUENOS AIRES  25 de Mayo   Del Valle    6854020  181        - 0     - 0

  FIBRA OPTICA OTROS SATELITAL WIMAX WIRELESS Total general  Unnamed: 13
0            2   - 0       975   - 0      664         7.218          NaN
1          - 0    10         1   - 0      - 0           192          NaN

-------------------  internet_tecno_nacional  ---------------------
    Año  Trimestre       ADSL Cablemodem Fibra óptica  Wireless    Otros  \
0  2022          3  1.395.277  6.031.970    2.871.541   557.110  235.230
1  2022          2  1.468.333  5.979.214    2.723.285   556.243  231.609

        Total        Periodo
0  11.091.128  Jul-Sept 2022
1  10.958.684   Abr-Jun 2022

-------------------  internet_fijo_veloc_bajada_prov  ---------------------
      Año  Trimestre        Provincia    Otros 0,256 Mbps 0,375 Mbps  \
0  2022.0        3.0     Buenos Aires   65,821         19        - 0
1  2022.0        3.0  Capital Federal  105,477         31        - 0

  0,625 Mbps 0,5 Mbps 0,512 Mbps 0,75 Mbps  ... 70 Mbps 71 Mbps 75 Mbps  \
0        - 0   29,774        192     4,611  ...   3,163     - 0  98,387
1        - 0      451         35     1,307  ...       3     - 0  30,482

  77 Mbps 78 Mbps 80 Mbps 81 Mbps 83 Mbps 82 Mbps 86 Mbps
0     - 0       2     223     - 0       1     - 0     - 0
1     - 0     - 0       8     - 0     - 0     - 0     - 0

[2 rows x 97 columns]

-------------------  indicadores_macro  ---------------------
    Año  Trimestre  IPC US  IPC AR USDARS oficial USDARS blue PBI millones
0  2013          1  232773     298           5,00        9,00    2.888.981
1  2013          2  233504     309           5,00        9,00    3.387.811

-------------------  internet_rango_vel_prov  ---------------------
    Año  Trimestre        Provincia  HASTA 512 kbps  + 512 Kbps - 1 Mbps  \
0  2022          3     Buenos Aires          29.985               27.709
1  2022          3  Capital Federal         517.000                5.742

  + 1 Mbps - 6 Mbps  + 6 Mbps - 10 Mbps  + 10 Mbps - 20 Mbps  \
0           290.315             297.915              267.044
1            34.371              67.829               51.946

   + 20 Mbps - 30 Mbps  + 30 Mbps    OTROS      Total
0              124.190  3.618.689   65.821  4.721.668
1               28.692  1.253.105  105.477  1.547.679

-------------------  internet_rango_vel  ---------------------
    Año  Trimestre  Hasta 512 kbps  Entre 512 Kbps y 1 Mbps  \
0  2022          3          33.013                   96.727
1  2022          2          33.667                   99.498

  Entre 1 Mbps y 6 Mbps Entre 6 Mbps y 10 Mbps Entre 10 Mbps y 20 Mbps  \
0             1.161.370              1.151.906                 823.505
1             1.193.090              1.197.030                 856.562

  Entre 20 Mbps y 30 Mbps Más de 30 Mbps    OTROS       Total  Unnamed: 11
0                 479.822      6.995.750  349.035  11.091.128          NaN
1                 485.321      6.741.922  351.594  10.958.684          NaN

-------------------  tecnologia_loc  ---------------------
     Unnamed: 0       Partido      Localidad  Unnamed: 3 Unnamed: 4  \
0           NaN  Bahía Blanca  Villa Bordeau         0.0        NaN
1  BUENOS AIRES           NaN            NaN         0.0         --

  CABLEMODEM DIALUP Unnamed: 7 Unnamed: 8 WIRELESS TELEFONIAFIJA Unnamed: 11  \
0         --     --         --        NaN       --            --         NaN
1        NaN    NaN         --         --      NaN           NaN          --

  Unnamed: 12       link            Latitud        Unnamed: 15
0          SI  6056020.0  -38,6472605094596                NaN
1          --        NaN  -38,7765069529222  -62,1851833537179

-------------------  internet_tecno_prov  ---------------------
    Año Trimestre        Provincia     ADSL Cablemodem Fibra óptica  Wireless  \
0  2022         3     Buenos Aires  339.648  2.748.325    1.436.433   126.846
1  2022         3  Capital Federal  140.791  1.240.125      129.218     5.758

    Otros      Total
0  70.416  4.721.668
1  31.787  1.547.679

-------------------  veloc_media_prov  ---------------------
    Año  Trimestre        Provincia  Mbps (Media de bajada)  Unnamed: 4  \
0  2022          3     Buenos Aires                      70         NaN
1  2022          3  Capital Federal                     101         NaN

   Unnamed: 5
0         NaN
1         NaN

-------------------  internet_bancha_bangosta  ---------------------
    Año  Trimestre Banda ancha fija  Dial up       Total        Periodo
0  2022          3       11.078.691   12.437  11.091.128  Jul-Sept 2022
1  2022          2       10.946.248   12.436  10.958.684   Abr-Jun 2022

-------------------  internet_fijo_veloc_bajada_loc  ---------------------
      Provincia     Partido        Localidad Link Indec Otros  0,256 mbps  \
0  BUENOS AIRES  25 de Mayo       25 de Mayo    6854100   NaN         NaN
1  BUENOS AIRES  25 de Mayo  Agustín Mosconi    6854010   NaN         NaN

   0,375 mbps 0,5 mbps  0,512 mbps  0,625 mbps  ... 75 mbps 78 mbps  80 mbps  \
0         NaN        2         NaN         NaN  ...     NaN     NaN      9.0
1         NaN      NaN         NaN         NaN  ...     NaN     NaN      NaN

  82 mbps 83 mbps  85 mbps  90 mbps 92 mbps  95 mbps 100 mbps
0     NaN     NaN      NaN      NaN     NaN      NaN      NaN
1     NaN     NaN      NaN      NaN     NaN      NaN      NaN

[2 rows x 83 columns]

-------------------  internet_fijo_poblacion  ---------------------
    Año  Trimestre        Provincia  Accesos por cada 100 hab
0  2022          3     Buenos Aires                        26
1  2022          3  Capital Federal                        50

-------------------  ingreso_internet_fijo_trimestral  ---------------------
    Año  Trimestre Ingresos (miles de pesos)        Periodo
0  2022          3                67.055.930  Jul-Sept 2022
1  2022          2                60.335.724   Abr-Jun 2022

-------------------  internet_fijo_hogar  ---------------------
    Año  Trimestre        Provincia Accesos por cada 100 hogares
0  2022          3     Buenos Aires                        78,11
1  2022          3  Capital Federal                       122,28

-------------------  veloc_media_nacional  ---------------------
    Año  Trimestre Mbps (Media de bajada)    Trimestre.1
0  2022          3                  62,46  Jul-Sept 2022
1  2022          2                  58,44   Abr-Jun 2022

-------------------  loc_tipo_conexion  ---------------------
     Unnamed: 0       Partido      Localidad ADSL Unnamed: 4 DIALUP  \
0           NaN  Bahía Blanca  Villa Bordeau  NaN        NaN     --
1  BUENOS AIRES           NaN   Villa Espora   --         --    NaN

  FIBRAOPTICA   4G Unnamed: 8 TELEFONIAFIJA Unnamed: 10 SATELITAL
0          --  NaN        NaN            --         NaN        --
1          --   --         --           NaN          --       NaN

-------------------  internet_bancha_bangosta_prov  ---------------------
    Año  Trimestre        Provincia Banda ancha fija Dial up      Total
0  2022          3     Buenos Aires        4.715.469   6.199  4.721.668
1  2022          3  Capital Federal        1.545.534   2.145  1.547.679

In [27]:
internet_tecno_nacional

,Año,Trimestre,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total,Periodo
0,2022,3,1.395.277,6.031.970,2.871.541,557.110,235.230,11.091.128,Jul-Sept 2022
1,2022,2,1.468.333,5.979.214,2.723.285,556.243,231.609,10.958.684,Abr-Jun 2022
2,2022,1,1.533.240,6.073.426,2.219.533,545.814,251.996,10.624.009,Ene-Mar 2022
3,2021,4,1.657.615,5.984.240,2.072.236,523.107,252.596,10.489.794,Oct-Dic 2021
4,2021,3,1.950.631,5.826.257,1.566.048,492.415,250.190,10.085.541,Jul-Sept 2021
5,2021,2,2.018.587,5.641.731,1.472.246,476.968,253.552,9.863.084,Abr-Jun 2021
6,2021,1,2.175.211,5.424.782,1.362.976,434.548,250.455,9.647.972,Ene-Mar 2021
7,2020,4,2.213.949,5.371.824,1.311.199,421.554,253.036,9.571.562,Oct-Dic 2020
8,2020,3,2.263.889,5.259.351,1.170.879,413.259,248.821,9.356.199,Jul-Sept 2020
9,2020,2,2.295.533,5.005.115,1.106.725,376.667,247.016,9.031.056,Abr-Jun 2020
10,2020,1,2.299.457,4.903.674,1.047.817,352.333,209.145,8.812.426,Ene-Mar 2020
11,2019,4,2.414.575,4.883.869,941.295,340.144,213.298,8.793.181,Oct-Dic 2019
12,2019,3,2.909.805,4.800.091,852.221,338.241,264.326,9.164.684,Jul-Sept 2019
13,2019,2,2.990.457,4.635.575,760.794,308.027,265.328,8.960.181,Abr-Jun 2019
14,2019,1,3.132.789,4.435.439,637.099,276.419,166.389,8.648.135,Ene-Mar 2019
15,2018,4,3.329.027,4.313.831,388.013,264.299,178.485,8.473.655,Oct-Dic 2018
16,2018,3,3.521.447,4.238.171,247.366,246.181,93.870,8.347.035,Jul-Sept 2018
17,2018,2,3.557.216,4.038.141,226.285,194.267,94.535,8.110.444,Abr-Jun 2018
18,2018,1,3.574.294,3.981.129,217.460,165.300,98.870,8.037.053,Ene-Mar 2018
19,2017,4,3.584.311,3.818.157,211.425,155.775,100.554,7.870.222,Oct-Dic 2017
20,2017,3,3.622.575,3.670.221,193.964,106.443,131.740,7.724.943,Jul-Sept 2017
21,2017,2,3.723.518,3.383.434,180.777,85.813,56.122,7.429.664,Abr-Jun 2017
22,2017,1,3.708.898,3.276.251,180.146,84.813,55.746,7.305.854,Ene-Mar 2017
23,2016,4,3.722.794,3.210.602,178.070,85.119,55.088,7.251.673,Oct-Dic 2016
24,2016,3,3.776.442,3.124.855,169.898,81.455,54.300,7.206.950,Jul-Sept 2016
25,2016,2,3.782.085,3.035.272,167.788,85.452,59.482,7.130.079,Abr-Jun 2016
26,2016,1,3.792.493,2.806.359,164.371,85.370,58.763,6.907.356,Ene-Mar 2016
27,2015,4,3.803.024,2.898.226,139.187,85.726,58.668,6.984.831,Oct-Dic 2015
28,2015,3,3.788.696,2.840.203,162.663,84.530,58.976,6.935.068,Jul-Sept 2015
29,2015,2,3.767.821,2.756.294,150.839,82.077,59.157,6.816.188,Abr-Jun 2015
30,2015,1,3.756.153,2.668.248,168.188,79.098,66.045,6.737.732,Ene-Mar 2015
31,2014,4,3.764.038,2.536.219,149.682,76.984,71.573,6.598.496,Oct-Dic 2014
32,2014,3,3.714.764,2.569.868,155.494,85.096,70.049,6.595.271,Jul-Sept 2014
33,2014,2,3.708.882,2.461.670,149.363,72.405,72.148,6.464.468,Abr-Jun 2014
34,2014,1,3.697.066,2.407.330,150.323,70.749,72.930,6.398.398,Ene-Mar 2014

In [28]:
internet_tecno_nacional.dtypes

Año               int64
Trimestre         int64
ADSL             object
Cablemodem       object
Fibra óptica     object
Wireless        float64
Otros           float64
Total            object
Periodo          object
dtype: object

In [29]:
internet_tecno_nacional['ADSL'] = internet_tecno_nacional['ADSL'].str.replace('.', '').astype(int)
internet_tecno_nacional['Cablemodem'] = internet_tecno_nacional['Cablemodem'].str.replace('.', '').astype(int)
internet_tecno_nacional['Fibra óptica'] = internet_tecno_nacional['Fibra óptica'].str.replace('.', '').astype(int)
internet_tecno_nacional['Wireless'] = internet_tecno_nacional['Wireless'].astype(str).str.replace('.', '').astype(int)
internet_tecno_nacional['Otros'] = internet_tecno_nacional['Otros'].astype(str).str.replace('.', '').astype(int)
internet_tecno_nacional['Total'] = internet_tecno_nacional['Total'].str.replace('.', '').astype(int)

In [30]:
internet_tecno_nacional

,Año,Trimestre,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total,Periodo
0,2022,3,1395277,6031970,2871541,55711,23523,11091128,Jul-Sept 2022
1,2022,2,1468333,5979214,2723285,556243,231609,10958684,Abr-Jun 2022
2,2022,1,1533240,6073426,2219533,545814,251996,10624009,Ene-Mar 2022
3,2021,4,1657615,5984240,2072236,523107,252596,10489794,Oct-Dic 2021
4,2021,3,1950631,5826257,1566048,492415,25019,10085541,Jul-Sept 2021
5,2021,2,2018587,5641731,1472246,476968,253552,9863084,Abr-Jun 2021
6,2021,1,2175211,5424782,1362976,434548,250455,9647972,Ene-Mar 2021
7,2020,4,2213949,5371824,1311199,421554,253036,9571562,Oct-Dic 2020
8,2020,3,2263889,5259351,1170879,413259,248821,9356199,Jul-Sept 2020
9,2020,2,2295533,5005115,1106725,376667,247016,9031056,Abr-Jun 2020
10,2020,1,2299457,4903674,1047817,352333,209145,8812426,Ene-Mar 2020
11,2019,4,2414575,4883869,941295,340144,213298,8793181,Oct-Dic 2019
12,2019,3,2909805,4800091,852221,338241,264326,9164684,Jul-Sept 2019
13,2019,2,2990457,4635575,760794,308027,265328,8960181,Abr-Jun 2019
14,2019,1,3132789,4435439,637099,276419,166389,8648135,Ene-Mar 2019
15,2018,4,3329027,4313831,388013,264299,178485,8473655,Oct-Dic 2018
16,2018,3,3521447,4238171,247366,246181,9387,8347035,Jul-Sept 2018
17,2018,2,3557216,4038141,226285,194267,94535,8110444,Abr-Jun 2018
18,2018,1,3574294,3981129,217460,1653,9887,8037053,Ene-Mar 2018
19,2017,4,3584311,3818157,211425,155775,100554,7870222,Oct-Dic 2017
20,2017,3,3622575,3670221,193964,106443,13174,7724943,Jul-Sept 2017
21,2017,2,3723518,3383434,180777,85813,56122,7429664,Abr-Jun 2017
22,2017,1,3708898,3276251,180146,84813,55746,7305854,Ene-Mar 2017
23,2016,4,3722794,3210602,178070,85119,55088,7251673,Oct-Dic 2016
24,2016,3,3776442,3124855,169898,81455,543,7206950,Jul-Sept 2016
25,2016,2,3782085,3035272,167788,85452,59482,7130079,Abr-Jun 2016
26,2016,1,3792493,2806359,164371,8537,58763,6907356,Ene-Mar 2016
27,2015,4,3803024,2898226,139187,85726,58668,6984831,Oct-Dic 2015
28,2015,3,3788696,2840203,162663,8453,58976,6935068,Jul-Sept 2015
29,2015,2,3767821,2756294,150839,82077,59157,6816188,Abr-Jun 2015
30,2015,1,3756153,2668248,168188,79098,66045,6737732,Ene-Mar 2015
31,2014,4,3764038,2536219,149682,76984,71573,6598496,Oct-Dic 2014
32,2014,3,3714764,2569868,155494,85096,70049,6595271,Jul-Sept 2014
33,2014,2,3708882,2461670,149363,72405,72148,6464468,Abr-Jun 2014
34,2014,1,3697066,2407330,150323,70749,7293,6398398,Ene-Mar 2014